node {
    def app

    stage('Clone repository') {
        checkout scm
    }

    stage('Build image') {
        app = docker.build("production/grubstack-core", "-f ./deployment/production/Dockerfile .")
    }

    stage('Test image') {
        app.inside {
            sh 'echo "Tests passed"'
        }
    }

    stage('Push image') {
        docker.withRegistry('https://docker.grubstack.app', 'grubstack-production-credentials') {
            app.push("latest")
        }
    }
}