FROM node:16-alpine as builder
# Set the working directory to /app inside the container
WORKDIR /app
# Copy app files
COPY . .
# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN npm ci 
# Build the app
RUN npm run build
# Install serve
RUN npm install -g serve
# Copy build files
COPY . /app
# Expose port
EXPOSE 3000
# Start serve
CMD ["npm", "run", "serve"]